/*
Package prompt handles the generation and templating of instructions for AI agents.

It uses standard Go templates to inject repository-specific context (like the
repository name and branch) into a set of behavioral mandates, ensuring the
AI agent understands its constraints and goals within the multi-gitter pipeline.
*/
package prompt

import (
	"bytes"
	"fmt"
	"os"
	"text/template"
)

// DefaultAgentTemplate is the markdown template used to instruct the AI agent.
const DefaultAgentTemplate = `
# multi-gitter-agent: AI Task

## 🛠 Context
You are a high-autonomy AI agent acting as a specialized "worker" in a multi-repository refactoring pipeline.
- **Orchestrator**: multi-gitter-agent (wrapping lindell/multi-gitter)
- **Target Repository**: {{ .Repository }}
{{- if .BaseBranch }}
- **Base Branch**: {{ .BaseBranch }}
{{- end }}
- **Operation Mode**: {{ if .DryRun }}DRY RUN (Simulated){{ else }}LIVE (Changes will be pushed){{ end }}

## 🎯 Objective
Your primary goal is to fulfill the following natural language request:
> {{ .UserPrompt }}

## 🛡 Security & Safety Mandates
1. **No Secrets**: NEVER hardcode API keys, tokens, or credentials. Do not log sensitive data.
2. **Scope**: Only modify files directly related to the objective. Avoid unrelated "cleanups" or stylistic changes unless specifically requested.
3. **Validation**: Ensure that any code you write is syntactically correct and follows the repository's established style.
4. **Minimalism**: Make the smallest change necessary to achieve the objective effectively.

## ⚙️ Operational Workflow
1. **Analysis**: Use your tools (grep, ls, find, cat) to deeply analyze the codebase and understand where the changes are needed.
2. **Actionability**: If the objective is NOT applicable to this repository, **do not modify any files**.
3. **No Git Management**: You are running in a temporary clone. Multi-gitter will detect your file changes and handle branching, committing, and PR creation. **Do not run git commands**.
4. **PR Triggering**: multi-gitter only creates a PR if files are modified. No modification = No PR.

## 📝 Execution Strategy
- Perform a thorough analysis of the codebase first.
- Apply the changes surgically and atomically.
- If you encounter an error or ambiguity, prioritize safety and avoid making partial or broken changes.
- Provide a brief, concise summary of what you did (or why you did nothing) at the end.
`

// Context holds the information needed to render the agent prompt.
type Context struct {
	UserPrompt string
	Repository string
	BaseBranch string
	DryRun     bool
}

// Registry manages available prompt templates.
type Registry struct {
	templates map[string]string
}

// NewRegistry creates a new template registry with the default template.
func NewRegistry() *Registry {
	r := &Registry{
		templates: make(map[string]string),
	}
	r.Register("default", DefaultAgentTemplate)
	return r
}

// Register adds a new template to the registry.
func (r *Registry) Register(name, content string) {
	r.templates[name] = content
}

// Render generates the final prompt string using the named template and context.
func (r *Registry) Render(name string, ctx Context) (string, error) {
	content, ok := r.templates[name]
	if !ok {
		// If not in registry, assume name is a raw template or use default
		content = r.templates["default"]
	}

	return render(content, ctx)
}

// RenderTemplateFile reads a template file and renders it with the provided context.
func RenderTemplateFile(path string, ctx Context) (string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("failed to read template file: %w", err)
	}

	return render(string(content), ctx)
}

func render(content string, ctx Context) (string, error) {
	tmpl, err := template.New("prompt").Parse(content)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, ctx); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

// RenderPRBody generates a formatted Markdown body for the Pull Request.
func RenderPRBody(ctx Context, agentName string, fullPrompt string) string {
	return fmt.Sprintf(`## 🤖 multi-gitter-agent PR

This Pull Request was automatically generated with AI using the **%s** agent.

### 🎯 Objective
%s

<details>
<summary><b>📜 Full AI Prompt</b></summary>

%s

</details>

---
*Generated by multi-gitter-agent*`, agentName, ctx.UserPrompt, fullPrompt)
}
